# CircuitSetup 6 Channel Energy Meter 2nd Add-on board config
# Assumes jumpers are both in the 2nd position

sensor:
#IC1 AddOn 2
############
  - platform: atm90e32
    cs_pin: 27
    release_device: true
    id: ${addon2_id1}
    phase_a:
      current:
        name: ${ct13_name} Current
        id: ct13Amps
      power:
        name: ${ct13_name} Power
        id: ct13Watts
      gain_voltage: ${voltage_cal1}
      gain_ct: ${current_cal_ct13}
    phase_b:
      current:
        name: ${ct14_name} Current
        id: ct14Amps
      power:
        name: ${ct14_name} Power
        id: ct14Watts
      gain_voltage: ${voltage_cal1}
      gain_ct: ${current_cal_ct14}
    phase_c:
      current:
        name: ${ct15_name} Current
        id: ct15Amps
      power:
        name: ${ct15_name} Power
        id: ct15Watts
      gain_voltage: ${voltage_cal1}
      gain_ct: ${current_cal_ct15}
    line_frequency: ${electric_freq}
    gain_pga: 1X
    update_interval: ${update_time}
    enable_offset_calibration: ${offset_calibration}
    enable_gain_calibration: ${gain_calibration}
#IC2 AddOn 2
############
  - platform: atm90e32
    release_device: true
    cs_pin: 17
    id: ${addon2_id2}
    phase_a:
      current:
        name: ${ct16_name} Current
        id: ct16Amps
      power:
        name: ${ct16_name} Power
        id: ct16Watts
      gain_voltage: ${voltage_cal2}
      gain_ct: ${current_cal_ct16}
    phase_b:
      current:
        name: ${ct17_name} Current
        id: ct17Amps
      power:
        name: ${ct17_name} Power
        id: ct17Watts
      gain_voltage: ${voltage_cal2}
      gain_ct: ${current_cal_ct17}
    phase_c:
      current:
        name: ${ct18_name} Current
        id: ct18Amps
      power:
        name: ${ct18_name} Power
        id: ct18Watts
      gain_voltage: ${voltage_cal2}
      gain_ct: ${current_cal_ct18}
    line_frequency: ${electric_freq}
    gain_pga: 1X
    update_interval: ${update_time}
    enable_offset_calibration: ${offset_calibration}
    enable_gain_calibration: ${gain_calibration}

#Total Current AddOn2
  - platform: template
    name: ${friendly_name} Total Current Add-on2
    id: totalAmpsAddOn2
    lambda: return id(ct13Amps).state + id(ct14Amps).state + id(ct15Amps).state + id(ct16Amps).state + id(ct17Amps).state + id(ct18Amps).state ;
    accuracy_decimals: 2
    unit_of_measurement: A
    device_class: current
    update_interval: ${update_time}

#Total Power AddOn2
  - platform: template
    name: ${friendly_name} Total Power Add-on2
    id: totalWattsAddOn2
    lambda: return id(ct13Watts).state + id(ct14Watts).state + id(ct15Watts).state + id(ct16Watts).state + id(ct17Watts).state + id(ct18Watts).state ;
    accuracy_decimals: 2
    unit_of_measurement: W
    device_class: power
    update_interval: ${update_time}
